<?php $preset=$settings['theme_preset']??'atelier'; $hasApiKey=!empty($settings['shipping_api_key']); ?>
<header class="page-head"><div><span class="eyebrow">Konfigurasi toko</span><h1>Tampilan & pengiriman</h1></div></header>
<form method="post" action="<?=url('/admin/settings')?>" class="settings-layout" id="settings-form"><?=csrf_field()?>
<div class="stack">
<section class="panel stack"><div class="setting-heading"><span>01</span><div><h2>Profil toko</h2><p>Tampil di header, footer, checkout, dan pesan WhatsApp.</p></div></div><div class="form-grid"><label>Nama toko<input name="store_name" value="<?=e($settings['store_name']??'')?>"></label><label>Tagline<input name="store_tagline" value="<?=e($settings['store_tagline']??'')?>"></label><label>WhatsApp toko<input name="store_whatsapp" value="<?=e($settings['store_whatsapp']??'')?>" placeholder="62812..."></label><label>Metode pengiriman<select name="shipping_mode" id="shipping-mode" onchange="toggleShipping()"><option value="manual" <?=($settings['shipping_mode']??'')==='manual'?'selected':''?>>Tarif manual buatan toko</option><option value="rajaongkir" <?=($settings['shipping_mode']??'')==='rajaongkir'?'selected':''?>>RajaOngkir V2, ongkir real-time</option><option value="disabled" <?=($settings['shipping_mode']??'')==='disabled'?'selected':''?>>Tanpa pengiriman</option></select></label></div><label>Alamat toko<textarea name="store_address" rows="3"><?=e($settings['store_address']??'')?></textarea></label></section>
<section class="panel stack shipping-config" id="rajaongkir-config"><div class="setting-heading"><span>02</span><div><h2>RajaOngkir V2</h2><p>Pelanggan mencari tujuan lalu memilih tarif kurir real-time saat checkout.</p></div></div><div class="setup-guide"><strong>Cara mendapat API key</strong><ol><li>Daftar di <a href="https://collaborator.komerce.id/registration" target="_blank" rel="noopener">dashboard Komerce ↗</a>.</li><li>Pilih RajaOngkir dan aktifkan paket Starter. Paket gratis menyediakan 100 hit cek ongkir per hari.</li><li>Buka menu API Key, buat key, lalu tempel di bawah.</li><li>Ambil ID district/subdistrict lokasi toko dari API pencarian tujuan RajaOngkir, lalu isi sebagai lokasi asal.</li></ol><a href="https://rajaongkir.com/docs/shipping-cost/getting_started/about" target="_blank" rel="noopener">Dokumentasi resmi API V2 ↗</a></div><div class="form-grid"><label>API key RajaOngkir<input type="password" name="shipping_api_key" autocomplete="new-password" placeholder="<?=$hasApiKey?'Key tersimpan. Kosongkan jika tidak diganti.':'Tempel API key di sini'?>"><small><?=$hasApiKey?'Status: key sudah tersimpan.':'Belum ada key tersimpan.'?></small></label><label>ID lokasi asal toko<input type="number" min="1" name="shipping_origin_id" value="<?=e($settings['shipping_origin_id']??'')?>" placeholder="Contoh: 31555"><small>ID district/subdistrict, bukan kode pos.</small></label><label>Nama lokasi asal<input name="shipping_origin_label" value="<?=e($settings['shipping_origin_label']??'')?>" placeholder="Kec. Coblong, Bandung"><small>Label internal agar ID mudah dikenali.</small></label><label>Kurir yang ditampilkan<input name="shipping_couriers" value="<?=e($settings['shipping_couriers']??'jne:sicepat:jnt:anteraja:ninja:tiki:pos')?>"><small>Pisahkan kode dengan titik dua.</small></label></div><button class="secondary-button" type="submit" formaction="<?=url('/admin/settings/shipping/test')?>">Tes API key RajaOngkir</button></section>
<section class="panel stack shipping-config" id="manual-config"><div class="setting-heading"><span>02</span><div><h2>Tarif pengiriman manual</h2><p>Total ongkir = tarif dasar + berat kilogram × tarif per kg.</p></div></div><div class="form-grid"><label>Nama zona baru<input name="zone_name" placeholder="Dalam Kota Bandung"></label><label>Tarif dasar<input type="number" min="0" name="base_cost" placeholder="10000"></label><label>Tambahan per kg<input type="number" min="0" name="cost_per_kg" placeholder="3000"></label></div><div class="zone-list"><?php foreach($zones as $zone):?><div><strong><?=e($zone['name'])?></strong><span><?=money($zone['base_cost'])?> dasar + <?=money($zone['cost_per_kg'])?>/kg</span></div><?php endforeach?><?php if(!$zones):?><p>Belum ada zona manual.</p><?php endif?></div></section>
</div>
<aside class="stack"><section class="panel stack theme-panel"><div class="setting-heading"><span>03</span><div><h2>Tema etalase</h2><p>Mengubah storefront pelanggan. Panel admin tidak ikut berubah.</p></div></div><label>Pilih preset<select name="theme_preset" id="theme-preset" onchange="applyPreset(this.value)"><option value="atelier" <?=$preset==='atelier'?'selected':''?>>Atelier Natural</option><option value="midnight" <?=$preset==='midnight'?'selected':''?>>Midnight Gold</option><option value="terracotta" <?=$preset==='terracotta'?'selected':''?>>Terracotta Market</option><option value="ocean" <?=$preset==='ocean'?'selected':''?>>Ocean Clean</option><option value="custom" <?=$preset==='custom'?'selected':''?>>Warna buatan sendiri</option></select></label><div class="color-settings"><label><span><b>Warna utama</b><small>Hero, tombol utama, dan footer.</small></span><span class="color-input"><input type="color" name="theme_primary" id="theme-primary" value="<?=e($settings['theme_primary']??'#173f35')?>"><code id="primary-code"></code></span></label><label><span><b>Warna aksen</b><small>Label promo dan sorotan.</small></span><span class="color-input"><input type="color" name="theme_accent" id="theme-accent" value="<?=e($settings['theme_accent']??'#ed7b45')?>"><code id="accent-code"></code></span></label><label><span><b>Warna latar</b><small>Katalog, detail produk, checkout.</small></span><span class="color-input"><input type="color" name="theme_background" id="theme-background" value="<?=e($settings['theme_background']??'#f5f0e7')?>"><code id="background-code"></code></span></label></div><div class="theme-preview" id="theme-preview"><span>Produk pilihan</span><strong>Karakter toko Anda</strong><p>Contoh warna kartu dan tombol.</p><button type="button">Belanja sekarang</button></div><small>Gunakan warna utama cukup gelap agar teks putih terbaca.</small><button class="button button-large">Simpan semua pengaturan</button></section></aside>
</form>
<script>
const presets={atelier:['#173f35','#ed7b45','#f5f0e7'],midnight:['#151515','#d7b46a','#eeeeea'],terracotta:['#713c2c','#e3a14f','#fbf1df'],ocean:['#123c55','#18a6a6','#eef7f6']},colorIds=['primary','accent','background'];
function refreshTheme(){const p=document.querySelector('#theme-preview');colorIds.forEach(x=>document.querySelector(`#${x}-code`).textContent=document.querySelector(`#theme-${x}`).value.toUpperCase());p.style.background=document.querySelector('#theme-background').value;p.style.color=document.querySelector('#theme-primary').value;p.style.borderLeftColor=document.querySelector('#theme-primary').value;p.querySelector('button').style.background=document.querySelector('#theme-accent').value}
function applyPreset(name){if(!presets[name])return;presets[name].forEach((v,i)=>document.querySelector(`#theme-${colorIds[i]}`).value=v);refreshTheme()}
function toggleShipping(){const mode=document.querySelector('#shipping-mode').value;document.querySelector('#rajaongkir-config').hidden=mode!=='rajaongkir';document.querySelector('#manual-config').hidden=mode!=='manual'}
colorIds.forEach(x=>document.querySelector(`#theme-${x}`).addEventListener('input',()=>{document.querySelector('#theme-preset').value='custom';refreshTheme()}));refreshTheme();toggleShipping();
</script>
