<?php

namespace App\Controllers;

use App\Core\Request;
use App\Core\Response;
use App\Services\RajaOngkirService;
use PDO;

final class AdminController
{
    private function guard(): void { require_admin(); }
    private function page(string $view, array $data=[]): string { $this->guard(); return view('layouts.admin',['content'=>view('admin.'.$view,$data)]); }
    public function dashboard(): string
    {
        $this->guard();
        $stats=['products'=>db()->query("SELECT COUNT(*) FROM products WHERE status='active'")->fetchColumn(),'low'=>db()->query('SELECT COUNT(*) FROM product_variants WHERE stock_qty<=low_stock_threshold')->fetchColumn(),'orders'=>db()->query("SELECT COUNT(*) FROM orders WHERE status='pending_whatsapp'")->fetchColumn(),'value'=>db()->query('SELECT COALESCE(SUM(stock_qty*COALESCE(cost,0)),0) FROM product_variants')->fetchColumn()];
        $recent=db()->query('SELECT * FROM orders ORDER BY id DESC LIMIT 6')->fetchAll(); return $this->page('dashboard',compact('stats','recent'));
    }
    public function categories(): string { return $this->page('categories',['items'=>db()->query('SELECT c.*,p.name parent_name FROM categories c LEFT JOIN categories p ON p.id=c.parent_id ORDER BY c.sort_order,c.name')->fetchAll()]); }
    public function saveCategory(Request $r): Response { $this->guard(); verify_csrf(); $name=trim($r->get('name')); db()->prepare('INSERT INTO categories(parent_id,name,slug,description,is_active) VALUES (NULLIF(?,0),?,?,?,?)')->execute([(int)$r->get('parent_id'),$name,slugify($name),$r->get('description'),$r->get('is_active')?1:0]); flash('success','Kategori ditambahkan.'); return redirect('/admin/categories'); }
    public function deleteCategory(Request $r,string $id): Response { $this->guard(); verify_csrf(); db()->prepare('DELETE FROM categories WHERE id=?')->execute([$id]); return redirect('/admin/categories'); }
    public function products(): string { $items=db()->query('SELECT p.*,c.name category_name,COUNT(v.id) variant_count,SUM(v.stock_qty) stock FROM products p LEFT JOIN categories c ON c.id=p.category_id LEFT JOIN product_variants v ON v.product_id=p.id GROUP BY p.id ORDER BY p.id DESC')->fetchAll(); return $this->page('products',compact('items')); }
    public function productForm(Request $r,?string $id=null): string { $product=$id?db()->prepare('SELECT * FROM products WHERE id=?'):null; if($product){$product->execute([$id]);$product=$product->fetch();} $variants=$id?db()->prepare('SELECT * FROM product_variants WHERE product_id=? ORDER BY id'):null;if($variants){$variants->execute([$id]);$variants=$variants->fetchAll();} return $this->page('product-form',['product'=>$product?:null,'variants'=>$variants?:[],'categories'=>db()->query("SELECT * FROM categories WHERE is_active=1 ORDER BY name")->fetchAll()]); }
    public function saveProduct(Request $r,?string $id=null): Response
    {
        $this->guard(); verify_csrf(); $pdo=db(); $pdo->beginTransaction();
        try { $name=trim($r->get('name')); $slug=slugify($r->get('slug')?:$name); $values=[(int)$r->get('category_id')?:null,$name,$slug,$r->get('base_sku'),$r->get('short_description'),$r->get('description'),(float)$r->get('base_price'),(float)$r->get('base_cost'),$r->get('unit','pcs'),(int)$r->get('weight_grams'),$r->get('is_featured')?1:0,$r->get('status','active')];
            if($id){$values[]=$id;$pdo->prepare('UPDATE products SET category_id=?,name=?,slug=?,base_sku=?,short_description=?,description=?,base_price=?,base_cost=?,unit=?,weight_grams=?,is_featured=?,status=? WHERE id=?')->execute($values);$productId=(int)$id;}else{$pdo->prepare('INSERT INTO products(category_id,name,slug,base_sku,short_description,description,base_price,base_cost,unit,weight_grams,is_featured,status) VALUES (?,?,?,?,?,?,?,?,?,?,?,?)')->execute($values);$productId=(int)$pdo->lastInsertId();}
            $seen=[]; foreach(($r->get('variants')?:[]) as $variant){if(empty($variant['sku']))continue;$v=[ $productId,trim($variant['name']?:'Default'),trim($variant['sku']),$variant['price']!==''?(float)$variant['price']:null,$variant['cost']!==''?(float)$variant['cost']:null,(int)($variant['stock_qty']??0),(int)($variant['low_stock_threshold']??5),!$seen?1:0];if(!empty($variant['id'])){$stmt=$pdo->prepare('UPDATE product_variants SET product_id=?,name=?,sku=?,price=?,cost=?,stock_qty=?,low_stock_threshold=?,is_default=? WHERE id=? AND product_id=?');$stmt->execute([...$v,$variant['id'],$productId]);$seen[]=(int)$variant['id'];}else{$pdo->prepare('INSERT INTO product_variants(product_id,name,sku,price,cost,stock_qty,low_stock_threshold,is_default) VALUES (?,?,?,?,?,?,?,?)')->execute($v);$seen[]=(int)$pdo->lastInsertId();}}
            if(!$seen){$sku=$r->get('base_sku')?:'PRD-'.$productId;$pdo->prepare("INSERT INTO product_variants(product_id,name,sku,stock_qty,is_default) VALUES (?,'Default',?,0,1)")->execute([$productId,$sku]);}
            $this->uploadImages($productId,$r->files['images']??null); $pdo->commit(); flash('success','Produk tersimpan.'); return redirect('/admin/products');
        }catch(\Throwable $e){$pdo->rollBack();throw $e;}
    }
    private function uploadImages(int $productId,?array $files): void
    {
        if(!$files||!is_array($files['name']))return;$finfo=new \finfo(FILEINFO_MIME_TYPE);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];
        foreach($files['tmp_name'] as $i=>$tmp){if(($files['error'][$i]??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)continue;$size=(int)($files['size'][$i]??0);$image=@getimagesize($tmp);$mime=$finfo->file($tmp);if(!is_uploaded_file($tmp)||!$image||$image[0]<1||$image[1]<1||$image[0]>5000||$image[1]>5000||($image[0]*$image[1])>20000000||!isset($allowed[$mime])||$size<1||$size>5*1024*1024)throw new \RuntimeException('Gambar harus JPG, PNG, atau WebP valid, maksimal 5 MB dan 5000 px.');$name=bin2hex(random_bytes(16)).'.'.$allowed[$mime];$directory=BASE_PATH.'/storage/uploads/products';if(!is_dir($directory)||!is_writable($directory))throw new \RuntimeException('Folder upload produk tidak dapat ditulis.');$target=$directory.'/'.$name;if(!move_uploaded_file($tmp,$target))throw new \RuntimeException('Upload gambar gagal.');$count=db()->prepare('SELECT COUNT(*) FROM product_images WHERE product_id=?');$count->execute([$productId]);db()->prepare('INSERT INTO product_images(product_id,image_path,is_primary) VALUES (?,?,?)')->execute([$productId,$name,$count->fetchColumn()?0:1]);}
    }
    public function deleteProduct(Request $r,string $id): Response {$this->guard();verify_csrf();db()->prepare("UPDATE products SET status='inactive' WHERE id=?")->execute([$id]);return redirect('/admin/products');}
    public function discounts(): string {return $this->page('discounts',['items'=>db()->query('SELECT d.*,p.name product_name,v.name variant_name FROM discounts d LEFT JOIN products p ON p.id=d.product_id LEFT JOIN product_variants v ON v.id=d.variant_id ORDER BY d.id DESC')->fetchAll(),'products'=>db()->query("SELECT id,name FROM products WHERE status='active'")->fetchAll()]);}
    public function saveDiscount(Request $r): Response {$this->guard();verify_csrf();db()->prepare('INSERT INTO discounts(product_id,name,discount_type,discount_value,starts_at,ends_at,is_active) VALUES (?,?,?,?,NULLIF(?,\'\'),NULLIF(?,\'\'),1)')->execute([(int)$r->get('product_id'),$r->get('name'),$r->get('discount_type'),(float)$r->get('discount_value'),$r->get('starts_at'),$r->get('ends_at')]);return redirect('/admin/discounts');}
    public function inventory(): string {$items=db()->query('SELECT v.*,p.name product_name FROM product_variants v JOIN products p ON p.id=v.product_id ORDER BY p.name,v.name')->fetchAll();return $this->page('inventory',compact('items'));}
    public function adjustStock(Request $r,string $id): Response {$this->guard();verify_csrf();$qty=(int)$r->get('quantity_change');$pdo=db();$pdo->beginTransaction();$s=$pdo->prepare('SELECT stock_qty FROM product_variants WHERE id=? FOR UPDATE');$s->execute([$id]);$before=(int)$s->fetchColumn();$after=$before+$qty;if($after<0)throw new \RuntimeException('Stok tidak boleh negatif.');$pdo->prepare('UPDATE product_variants SET stock_qty=? WHERE id=?')->execute([$after,$id]);$pdo->prepare('INSERT INTO stock_movements(variant_id,movement_type,quantity_change,stock_before,stock_after,notes,user_id) VALUES (?,?,?,?,?,?,?)')->execute([$id,'adjustment',$qty,$before,$after,$r->get('notes'),auth()['id']]);$pdo->commit();return redirect('/admin/inventory');}
    public function opnames(): string {$items=db()->query('SELECT o.*,u.name creator FROM stock_opnames o JOIN users u ON u.id=o.created_by ORDER BY o.id DESC')->fetchAll();return $this->page('opnames',compact('items'));}
    public function createOpname(Request $r): Response {$this->guard();verify_csrf();$pdo=db();$pdo->beginTransaction();$num='OP-'.date('Ymd-His');$pdo->prepare("INSERT INTO stock_opnames(opname_number,status,started_at,notes,created_by) VALUES (?,'counting',NOW(),?,?)")->execute([$num,$r->get('notes'),auth()['id']]);$id=$pdo->lastInsertId();$pdo->prepare('INSERT INTO stock_opname_items(stock_opname_id,variant_id,system_qty,unit_cost_snapshot) SELECT ?,id,stock_qty,COALESCE(cost,0) FROM product_variants WHERE is_active=1')->execute([$id]);$pdo->commit();return redirect('/admin/stock-opnames/'.$id);}
    public function showOpname(Request $r,string $id): string {$s=db()->prepare('SELECT * FROM stock_opnames WHERE id=?');$s->execute([$id]);$opname=$s->fetch();$q=db()->prepare('SELECT i.*,p.name product_name,v.name variant_name,v.sku FROM stock_opname_items i JOIN product_variants v ON v.id=i.variant_id JOIN products p ON p.id=v.product_id WHERE i.stock_opname_id=?');$q->execute([$id]);return $this->page('opname-show',['opname'=>$opname,'items'=>$q->fetchAll()]);}
    public function completeOpname(Request $r,string $id): Response {$this->guard();verify_csrf();$pdo=db();$pdo->beginTransaction();$s=$pdo->prepare('SELECT status FROM stock_opnames WHERE id=? FOR UPDATE');$s->execute([$id]);if($s->fetchColumn()==='completed')throw new \RuntimeException('Opname sudah selesai.');foreach($r->get('physical',[]) as $itemId=>$physical){$q=$pdo->prepare('SELECT * FROM stock_opname_items WHERE id=? AND stock_opname_id=?');$q->execute([$itemId,$id]);$item=$q->fetch();if(!$item)continue;$physical=(int)$physical;$diff=$physical-(int)$item['system_qty'];$pdo->prepare('UPDATE stock_opname_items SET physical_qty=?,difference_qty=?,counted_by=?,counted_at=NOW() WHERE id=?')->execute([$physical,$diff,auth()['id'],$itemId]);$current=$pdo->prepare('SELECT stock_qty FROM product_variants WHERE id=? FOR UPDATE');$current->execute([$item['variant_id']]);$before=(int)$current->fetchColumn();$pdo->prepare('UPDATE product_variants SET stock_qty=? WHERE id=?')->execute([$physical,$item['variant_id']]);$pdo->prepare("INSERT INTO stock_movements(variant_id,movement_type,quantity_change,stock_before,stock_after,reference_type,reference_id,user_id) VALUES (?,'stock_opname',?,?,?,'stock_opname',?,?)")->execute([$item['variant_id'],$diff,$before,$physical,$id,auth()['id']]);}$pdo->prepare("UPDATE stock_opnames SET status='completed',completed_at=NOW(),completed_by=? WHERE id=?")->execute([auth()['id'],$id]);$pdo->commit();return redirect('/admin/stock-opnames');}
    public function orders(): string {$items=db()->query('SELECT * FROM orders ORDER BY id DESC')->fetchAll();return $this->page('orders',compact('items'));}
    public function updateOrder(Request $r,string $id): Response {$this->guard();verify_csrf();$status=$r->get('status');if(!in_array($status,['pending_whatsapp','confirmed','completed','cancelled'],true))throw new \RuntimeException('Status pesanan tidak valid.');$pdo=db();$pdo->beginTransaction();$q=$pdo->prepare('SELECT status FROM orders WHERE id=? FOR UPDATE');$q->execute([$id]);$old=$q->fetchColumn();$items=$pdo->prepare('SELECT * FROM order_items WHERE order_id=?');$items->execute([$id]);$items=$items->fetchAll();if($status==='confirmed'&&$old==='pending_whatsapp'){foreach($items as $item){$v=$pdo->prepare('SELECT stock_qty FROM product_variants WHERE id=? FOR UPDATE');$v->execute([$item['variant_id']]);$before=(int)$v->fetchColumn();$after=$before-(int)$item['quantity'];if($after<0)throw new \RuntimeException('Stok tidak cukup untuk konfirmasi.');$pdo->prepare('UPDATE product_variants SET stock_qty=? WHERE id=?')->execute([$after,$item['variant_id']]);$pdo->prepare("INSERT INTO stock_movements(variant_id,movement_type,quantity_change,stock_before,stock_after,reference_type,reference_id,user_id) VALUES (?,'order',?,?,?,?,?,?)")->execute([$item['variant_id'],-$item['quantity'],$before,$after,'order',$id,auth()['id']]);}}elseif($status==='cancelled'&&$old==='confirmed'){foreach($items as $item){$v=$pdo->prepare('SELECT stock_qty FROM product_variants WHERE id=? FOR UPDATE');$v->execute([$item['variant_id']]);$before=(int)$v->fetchColumn();$after=$before+(int)$item['quantity'];$pdo->prepare('UPDATE product_variants SET stock_qty=? WHERE id=?')->execute([$after,$item['variant_id']]);$pdo->prepare("INSERT INTO stock_movements(variant_id,movement_type,quantity_change,stock_before,stock_after,reference_type,reference_id,user_id) VALUES (?,'order_cancelled',?,?,?,?,?,?)")->execute([$item['variant_id'],$item['quantity'],$before,$after,'order',$id,auth()['id']]);}}$pdo->prepare('UPDATE orders SET status=?,confirmed_at=IF(?=\'confirmed\',NOW(),confirmed_at) WHERE id=?')->execute([$status,$status,$id]);$pdo->commit();return redirect('/admin/orders');}
    public function settings(): string {return $this->page('settings',['settings'=>db()->query('SELECT setting_key,setting_value FROM settings')->fetchAll(PDO::FETCH_KEY_PAIR),'zones'=>db()->query('SELECT * FROM shipping_zones ORDER BY name')->fetchAll()]);}
    public function saveSettings(Request $r): Response {$this->guard();verify_csrf();$keys=['store_name','store_tagline','store_whatsapp','store_address','shipping_mode','shipping_origin_id','shipping_origin_label','shipping_couriers','theme_preset','theme_primary','theme_accent','theme_background'];$s=db()->prepare("INSERT INTO settings(setting_key,setting_value,is_public) VALUES (?,?,?) ON DUPLICATE KEY UPDATE setting_value=VALUES(setting_value),is_public=VALUES(is_public)");foreach($keys as $key)$s->execute([$key,(string)$r->get($key),1]);if((string)$r->get('shipping_api_key')!=='')$s->execute(['shipping_api_key',(string)$r->get('shipping_api_key'),0]);if($r->get('zone_name'))db()->prepare('INSERT INTO shipping_zones(name,base_cost,cost_per_kg,is_active) VALUES (?,?,?,1)')->execute([$r->get('zone_name'),(float)$r->get('base_cost'),(float)$r->get('cost_per_kg')]);flash('success','Pengaturan tersimpan.');return redirect('/admin/settings');}

    public function testShipping(Request $r): Response
    {
        $this->guard(); verify_csrf();
        try {
            $key = trim((string) $r->get('shipping_api_key')) ?: (string) setting('shipping_api_key', '');
            $results = (new RajaOngkirService($key))->searchDestinations('Jakarta', 1);
            if (!$results) throw new \RuntimeException('API aktif, tetapi pencarian lokasi tidak mengembalikan data.');
            flash('success', 'Koneksi RajaOngkir berhasil. API key aktif.');
        } catch (\Throwable $e) {
            flash('error', 'Tes RajaOngkir gagal: ' . $e->getMessage());
        }
        return redirect('/admin/settings');
    }
}
