<?php

namespace App\Controllers;

use App\Core\Request;
use App\Core\Response;
use App\Services\RajaOngkirService;

final class StoreController
{
    private function layout(string $view,array $data=[]): string {return view('layouts.store',['content'=>view('storefront.'.$view,$data)]);}
    private function productQuery(): string {return "SELECT p.*,c.name category_name,i.image_path,v.id variant_id,v.name variant_name,v.sku,v.stock_qty,COALESCE(v.price,p.base_price) price,d.discount_type,d.discount_value FROM products p LEFT JOIN categories c ON c.id=p.category_id JOIN product_variants v ON v.product_id=p.id AND v.is_default=1 LEFT JOIN product_images i ON i.id=(SELECT pi.id FROM product_images pi WHERE pi.product_id=p.id ORDER BY pi.is_primary DESC,pi.sort_order,pi.id LIMIT 1) LEFT JOIN discounts d ON d.id=(SELECT d2.id FROM discounts d2 WHERE d2.is_active=1 AND (d2.variant_id=v.id OR (d2.product_id=p.id AND d2.variant_id IS NULL)) AND (d2.starts_at IS NULL OR d2.starts_at<=NOW()) AND (d2.ends_at IS NULL OR d2.ends_at>=NOW()) ORDER BY (d2.variant_id=v.id) DESC,d2.priority DESC,d2.id DESC LIMIT 1) WHERE p.status='active'";}
    private function price(array $row): array {$base=(float)$row['price'];$discount=0;if($row['discount_type']==='percentage')$discount=$base*((float)$row['discount_value']/100);elseif($row['discount_type']==='fixed')$discount=(float)$row['discount_value'];return ['base'=>$base,'discount'=>min($base,$discount),'final'=>max(0,$base-$discount)];}
    public function home(): string {$limit=max(4,min(16,(int)setting('homepage_products_count',8)));$items=db()->query($this->productQuery().' ORDER BY p.is_featured DESC,p.id DESC LIMIT '.$limit)->fetchAll();foreach($items as &$x)$x['pricing']=$this->price($x);$categories=db()->query("SELECT c.*,COUNT(p.id) total FROM categories c LEFT JOIN products p ON p.category_id=c.id AND p.status='active' WHERE c.is_active=1 GROUP BY c.id ORDER BY total DESC LIMIT 6")->fetchAll();return $this->layout('home',compact('items','categories'));}
    public function catalog(Request $r,?string $slug=null): string {$sql=$this->productQuery();$params=[];if($slug){$sql.=' AND c.slug=?';$params[]=$slug;}if($q=trim((string)$r->get('q'))){$sql.=' AND (p.name LIKE ? OR p.short_description LIKE ?)';$params[]=$params[]='%'.$q.'%';}$sql.=' ORDER BY p.id DESC';$s=db()->prepare($sql);$s->execute($params);$items=$s->fetchAll();foreach($items as &$x)$x['pricing']=$this->price($x);return $this->layout('catalog',compact('items','slug'));}
    public function product(Request $r,string $slug): string {$s=db()->prepare('SELECT p.*,c.name category_name,c.slug category_slug FROM products p LEFT JOIN categories c ON c.id=p.category_id WHERE p.slug=? AND p.status=\'active\'');$s->execute([$slug]);$product=$s->fetch();if(!$product)throw new \RuntimeException('Produk tidak ditemukan.');$v=db()->prepare("SELECT v.*,d.discount_type,d.discount_value FROM product_variants v LEFT JOIN discounts d ON d.id=(SELECT d2.id FROM discounts d2 WHERE d2.is_active=1 AND (d2.variant_id=v.id OR (d2.product_id=v.product_id AND d2.variant_id IS NULL)) AND (d2.starts_at IS NULL OR d2.starts_at<=NOW()) AND (d2.ends_at IS NULL OR d2.ends_at>=NOW()) ORDER BY (d2.variant_id=v.id) DESC,d2.priority DESC,d2.id DESC LIMIT 1) WHERE v.product_id=? AND v.is_active=1 ORDER BY v.is_default DESC,v.id");$v->execute([$product['id']]);$variants=$v->fetchAll();foreach($variants as &$x){$x['price']=$x['price']??$product['base_price'];$x['pricing']=$this->price($x);}$i=db()->prepare('SELECT * FROM product_images WHERE product_id=? ORDER BY is_primary DESC,sort_order,id');$i->execute([$product['id']]);return $this->layout('product',['product'=>$product,'variants'=>$variants,'images'=>$i->fetchAll()]);}
    public function image(Request $r,string $file): Response {return $this->media($r,'products',$file);}
    public function media(Request $r,string $collection,string $file): Response {$allowed=['products','branding','homepage','footer'];if(!in_array($collection,$allowed,true))return new Response('',404);$file=basename($file);$path=BASE_PATH.'/storage/uploads/'.$collection.'/'.$file;if(!is_file($path)&&!str_contains($file,'.')){$files=glob(BASE_PATH.'/storage/uploads/'.$collection.'/'.$file.'.*')?:[];$path=$files[0]??$path;}if(!is_file($path))return new Response('',404);$mime=(new \finfo(FILEINFO_MIME_TYPE))->file($path);if(!in_array($mime,['image/jpeg','image/png','image/webp','image/x-icon','image/vnd.microsoft.icon'],true))return new Response('',404);return new Response(file_get_contents($path),200,['Content-Type'=>$mime,'Cache-Control'=>'public, max-age=31536000, immutable','X-Content-Type-Options'=>'nosniff']);}
    public function addCart(Request $r): Response {verify_csrf();$id=(int)$r->get('variant_id');$qty=(int)$r->get('quantity',1);if($id<1||$qty<1||$qty>100){flash('error','Jumlah produk tidak valid.');return redirect('/produk');}$s=db()->prepare("SELECT v.id,v.stock_qty FROM product_variants v JOIN products p ON p.id=v.product_id WHERE v.id=? AND v.is_active=1 AND p.status='active'");$s->execute([$id]);$v=$s->fetch();if(!$v||$qty>$v['stock_qty']){flash('error','Jumlah melebihi stok tersedia.');return redirect('/produk');}$_SESSION['cart'][$id]=min((int)$v['stock_qty'],($_SESSION['cart'][$id]??0)+$qty);flash('success','Produk masuk keranjang.');return redirect('/keranjang');}
    private function cartItems(): array {$cart=$_SESSION['cart']??[];if(!$cart)return [];$ids=array_map('intval',array_keys($cart));$sql="SELECT p.id product_id,p.name,p.slug,p.base_price,v.id variant_id,v.name variant_name,v.sku,v.price,v.stock_qty,COALESCE(v.weight_grams,p.weight_grams) weight_grams,d.discount_type,d.discount_value FROM product_variants v JOIN products p ON p.id=v.product_id LEFT JOIN discounts d ON d.id=(SELECT d2.id FROM discounts d2 WHERE d2.is_active=1 AND (d2.variant_id=v.id OR (d2.product_id=p.id AND d2.variant_id IS NULL)) AND (d2.starts_at IS NULL OR d2.starts_at<=NOW()) AND (d2.ends_at IS NULL OR d2.ends_at>=NOW()) ORDER BY (d2.variant_id=v.id) DESC,d2.priority DESC,d2.id DESC LIMIT 1) WHERE v.id IN (".implode(',',$ids).")";$items=db()->query($sql)->fetchAll();foreach($items as &$x){$x['price']=$x['price']??$x['base_price'];$x['pricing']=$this->price($x);$x['quantity']=min((int)$cart[$x['variant_id']],(int)$x['stock_qty']);$x['total']=$x['pricing']['final']*$x['quantity'];}return $items;}
    public function cart(): string {return $this->layout('cart',['items'=>$this->cartItems()]);}
    public function updateCart(Request $r): Response {verify_csrf();foreach((array)$r->get('quantity',[]) as $id=>$qty){$id=(int)$id;$qty=(int)$qty;if($id<1||$qty<=0)unset($_SESSION['cart'][$id]);else $_SESSION['cart'][$id]=min(100,$qty);}flash('success','Jumlah produk di keranjang diperbarui.');return redirect('/keranjang');}
    public function removeCart(Request $r,string $id): Response {verify_csrf();unset($_SESSION['cart'][(int)$id]);flash('success','Produk dihapus dari keranjang.');return redirect('/keranjang');}
    public function checkout(): string {$items=$this->cartItems();if(!$items)return redirect('/keranjang')->send();$zones=db()->query('SELECT * FROM shipping_zones WHERE is_active=1 ORDER BY name')->fetchAll();return $this->layout('checkout',compact('items','zones'));}
    public function shippingDestinations(Request $r): Response
    {
        try {$items=(new RajaOngkirService((string)setting('shipping_api_key','')))->searchDestinations((string)$r->get('q'));return new Response(json_encode(['data'=>$items],JSON_UNESCAPED_UNICODE),200,['Content-Type'=>'application/json']);}
        catch (\Throwable $e) {return new Response(json_encode(['message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE),422,['Content-Type'=>'application/json']);}
    }
    public function shippingRates(Request $r): Response
    {
        try {verify_csrf();$items=$this->cartItems();$weight=max(1,array_sum(array_map(fn($x)=>(int)$x['weight_grams']*$x['quantity'],$items)));$rates=(new RajaOngkirService((string)setting('shipping_api_key','')))->calculate((int)setting('shipping_origin_id',0),(int)$r->get('destination_id'),$weight,(string)setting('shipping_couriers','jne:sicepat:jnt:anteraja:ninja:tiki:pos'));return new Response(json_encode(['data'=>$rates],JSON_UNESCAPED_UNICODE),200,['Content-Type'=>'application/json']);}
        catch (\Throwable $e) {return new Response(json_encode(['message'=>$e->getMessage()],JSON_UNESCAPED_UNICODE),422,['Content-Type'=>'application/json']);}
    }
    public function placeOrderV2(Request $r): Response
    {
        verify_csrf(); $items=$this->cartItems();
        if(!$items) throw new \RuntimeException('Keranjang kosong.');
        foreach(['name','phone','address'] as $field) if(!trim((string)$r->get($field))) throw new \RuntimeException('Data pelanggan belum lengkap.');
        if (!preg_match('/^62[0-9]{8,13}$/', preg_replace('/\D+/', '', (string) $r->get('phone')))) throw new \RuntimeException('Nomor WhatsApp harus memakai format 628xxxxxxxxxx.');
        $shipping=0; $shippingName='Tanpa pengiriman'; $mode=setting('shipping_mode','manual');
        if($mode==='rajaongkir') {
            $destination=(int)$r->get('destination_id'); $selected=(string)$r->get('shipping_service');
            if(!$destination||$selected==='') throw new \RuntimeException('Pilih tujuan dan layanan pengiriman.');
            $weight=max(1,array_sum(array_map(fn($x)=>(int)$x['weight_grams']*$x['quantity'],$items)));
            $rates=(new RajaOngkirService((string)setting('shipping_api_key','')))->calculate((int)setting('shipping_origin_id',0),$destination,$weight,(string)setting('shipping_couriers','jne:sicepat:jnt:anteraja:ninja:tiki:pos'));
            $match=null; foreach($rates as $rate) if(($rate['courier'].'|'.$rate['service'])===$selected){$match=$rate;break;}
            if(!$match) throw new \RuntimeException('Layanan pengiriman tidak valid atau tarif sudah berubah.');
            $shipping=$match['cost']; $shippingName=trim($match['courier_name'].' '.$match['service'].' '.$match['etd']);
        } elseif($mode==='manual'&&$r->get('shipping_zone')) {
            $stmt=db()->prepare('SELECT * FROM shipping_zones WHERE id=? AND is_active=1'); $stmt->execute([$r->get('shipping_zone')]); $zone=$stmt->fetch();
            if($zone){$weight=array_sum(array_map(fn($x)=>(int)$x['weight_grams']*$x['quantity'],$items));$shipping=(float)$zone['base_cost']+ceil($weight/1000)*(float)$zone['cost_per_kg'];$shippingName=$zone['name'];}
        }
        $subtotal=array_sum(array_column($items,'total')); $number='ORD-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6)); $pdo=db(); $pdo->beginTransaction();
        try {
            $pdo->prepare("INSERT INTO customers(name,phone,email) VALUES (?,?,NULLIF(?,''))")->execute([$r->get('name'),$r->get('phone'),$r->get('email')]); $customerId=$pdo->lastInsertId();
            $address=json_encode(['address'=>$r->get('address'),'destination_id'=>$r->get('destination_id'),'destination_label'=>$r->get('destination_label')],JSON_UNESCAPED_UNICODE);
            $pdo->prepare('INSERT INTO orders(order_number,customer_id,customer_name,customer_phone,subtotal,shipping_cost,grand_total,shipping_method,shipping_address_json,customer_notes,whatsapp_opened_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW())')->execute([$number,$customerId,$r->get('name'),$r->get('phone'),$subtotal,$shipping,$subtotal+$shipping,$shippingName,$address,$r->get('notes')]);
            $orderId=$pdo->lastInsertId(); $stmt=$pdo->prepare('INSERT INTO order_items(order_id,product_id,variant_id,product_name,variant_name,sku,unit_price,discount_amount,quantity,line_total) VALUES (?,?,?,?,?,?,?,?,?,?)');
            foreach($items as $item)$stmt->execute([$orderId,$item['product_id'],$item['variant_id'],$item['name'],$item['variant_name'],$item['sku'],$item['pricing']['base'],$item['pricing']['discount'],$item['quantity'],$item['total']]);
            $pdo->commit(); unset($_SESSION['cart']);
            $lines=['Halo, saya ingin memesan:','','No. Pesanan: '.$number,'']; foreach($items as $i=>$item)$lines[]=($i+1).'. '.$item['name'].' ('.$item['variant_name'].') '.$item['quantity'].' x '.money($item['pricing']['final']).' = '.money($item['total']);
            array_push($lines,'','Subtotal: '.money($subtotal),'Pengiriman: '.$shippingName.' - '.money($shipping),'Total: '.money($subtotal+$shipping),'','Nama: '.$r->get('name'),'Alamat: '.$r->get('address')); if($r->get('notes'))$lines[]='Catatan: '.$r->get('notes');
            return Response::redirect('https://wa.me/'.preg_replace('/\D/','',setting('store_whatsapp','')).'?text='.rawurlencode(implode("\n",$lines)));
        } catch(\Throwable $e) {if($pdo->inTransaction())$pdo->rollBack();throw $e;}
    }
    public function placeOrder(Request $r): Response {verify_csrf();$items=$this->cartItems();if(!$items)throw new \RuntimeException('Keranjang kosong.');foreach(['name','phone','address'] as $f)if(!trim((string)$r->get($f)))throw new \RuntimeException('Data pelanggan belum lengkap.');$shipping=0;$zoneName='Tanpa pengiriman';if(setting('shipping_mode')==='manual'&&$r->get('shipping_zone')){$z=db()->prepare('SELECT * FROM shipping_zones WHERE id=? AND is_active=1');$z->execute([$r->get('shipping_zone')]);$zone=$z->fetch();if($zone){$weight=array_sum(array_map(fn($x)=>(int)$x['weight_grams']*$x['quantity'], $items));$shipping=(float)$zone['base_cost']+ceil($weight/1000)*(float)$zone['cost_per_kg'];$zoneName=$zone['name'];}}$subtotal=array_sum(array_column($items,'total'));$number='ORD-'.date('Ymd').'-'.strtoupper(substr(bin2hex(random_bytes(3)),0,6));$pdo=db();$pdo->beginTransaction();try{$pdo->prepare('INSERT INTO customers(name,phone,email) VALUES (?,?,NULLIF(?,\'\'))')->execute([$r->get('name'),$r->get('phone'),$r->get('email')]);$customerId=$pdo->lastInsertId();$address=json_encode(['address'=>$r->get('address')]);$pdo->prepare("INSERT INTO orders(order_number,customer_id,customer_name,customer_phone,subtotal,shipping_cost,grand_total,shipping_method,shipping_address_json,customer_notes,whatsapp_opened_at) VALUES (?,?,?,?,?,?,?,?,?,?,NOW())")->execute([$number,$customerId,$r->get('name'),$r->get('phone'),$subtotal,$shipping,$subtotal+$shipping,$zoneName,$address,$r->get('notes')]);$orderId=$pdo->lastInsertId();$s=$pdo->prepare('INSERT INTO order_items(order_id,product_id,variant_id,product_name,variant_name,sku,unit_price,discount_amount,quantity,line_total) VALUES (?,?,?,?,?,?,?,?,?,?)');foreach($items as $x)$s->execute([$orderId,$x['product_id'],$x['variant_id'],$x['name'],$x['variant_name'],$x['sku'],$x['pricing']['base'],$x['pricing']['discount'],$x['quantity'],$x['total']]);$pdo->commit();unset($_SESSION['cart']);$lines=["Halo, saya ingin memesan:","","No. Pesanan: {$number}",""];foreach($items as $i=>$x)$lines[]=($i+1).'. '.$x['name'].' ('.$x['variant_name'].') '.$x['quantity'].' x '.money($x['pricing']['final']).' = '.money($x['total']);$lines[]='';$lines[]='Subtotal: '.money($subtotal);$lines[]='Pengiriman: '.money($shipping);$lines[]='Total: '.money($subtotal+$shipping);$lines[]='';$lines[]='Nama: '.$r->get('name');$lines[]='Alamat: '.$r->get('address');if($r->get('notes'))$lines[]='Catatan: '.$r->get('notes');$wa=preg_replace('/\D/','',setting('store_whatsapp',''));return Response::redirect('https://wa.me/'.$wa.'?text='.rawurlencode(implode("\n",$lines)));}catch(\Throwable $e){$pdo->rollBack();throw $e;}}
}
